name: CI/CD FlexibleCalendar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore FlexibleCalendar/FlexibleCalendar.csproj

      - name: Build project
        run: dotnet build FlexibleCalendar/FlexibleCalendar.csproj --configuration Release --no-restore

  pack:
    name: Pack
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Pack NuGet package
        run: dotnet pack FlexibleCalendar/FlexibleCalendar.csproj --configuration Release --output ./nupkg

      - name: Upload NuGet package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./nupkg/*.nupkg

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: pack
    if: github.event_name != 'pull_request'
    steps:
      - name: Download NuGet package
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: ./nupkg

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Push to NuGet
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
            --source https://api.nuget.org/v3/index.json \
            --api-key "${{ secrets.NUGET_API_KEY }}" \
            --skip-duplicate