name: CI/CD FlexibleCalendar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.current_version.outputs.version }}
      main_version: ${{ steps.main_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch main branch
        run: git fetch origin main:refs/remotes/origin/main --depth=1

      - name: Get current version
        id: current_version
        run: |
          version=$(sed -n 's|.*<Version>\(.*\)</Version>.*|\1|p' FlexibleCalendar/FlexibleCalendar.csproj)
          echo "Current version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Get main branch version
        id: main_version
        run: |
          git show origin/main:FlexibleCalendar/FlexibleCalendar.csproj > main_FlexibleCalendar.csproj
          main_version=$(sed -n 's|.*<Version>\(.*\)</Version>.*|\1|p' main_FlexibleCalendar.csproj)
          echo "Main version: $main_version"
          echo "version=$main_version" >> $GITHUB_OUTPUT

      - name: Check if version changed
        run: |
          if [ "${{ steps.current_version.outputs.version }}" = "${{ steps.main_version.outputs.version }}" ]; then
            echo "Version did not change. Skipping pipeline."
            exit 1
          fi
          echo "Version changed. Continuing pipeline."

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore FlexibleCalendar/FlexibleCalendar.csproj

      - name: Build project
        run: dotnet build FlexibleCalendar/FlexibleCalendar.csproj --configuration Release --no-restore

  pack:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Pack NuGet package
        run: dotnet pack FlexibleCalendar/FlexibleCalendar.csproj --configuration Release --no-build --output ./nupkg

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./nupkg/*.nupkg

  publish:
    runs-on: ubuntu-latest
    needs: pack
    if: github.event_name != 'pull_request'
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: ./nupkg

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Push to NuGet
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
            --source https://api.nuget.org/v3/index.json \
            --api-key "${{ secrets.NUGET_API_KEY }}" \
            --skip-duplicate